import:
  - ~/.config/alacritty/colors.yml
env:
  WINIT_X11_SCALE_FACTOR: "1"
font:
  normal:
    family: Iosevka SS07
  size: 14
  offset:
    y: 2
key_bindings:
  - action: IncreaseFontSize
    key: Asterisk
    mods: Control
  - action: DecreaseFontSize
    key: Minus
    mods: Control
  - chars: "\u0017"
    key: Back
    mods: Control
mouse:
  hide_when_typing: true
scrolling:
  history: 100000
  multiplier: 4
selection:
  unfocused_hollow: true
window:
  padding:
    x: 36
    y: 36
mouse_bindings:
  - action: Quit
    mouse: Middle
