colors:
    primary:
        background: '0x151515'
        foreground: '0xd0d0d0'
    normal:
        black: '0x151515'
        red: '0xac4142'
        green: '0x90a959'
        yellow: '0xf4bf75'
        blue: '0x6a9fb5'
        magenta: '0xaa759f'
        cyan: '0x75b5aa'
        white: '0xd0d0d0'
    bright:
        black: '0x505050'
        red: '0xac4142'
        green: '0x90a959'
        yellow: '0xf4bf75'
        blue: '0x6a9fb5'
        magenta: '0xaa759f'
        cyan: '0x75b5aa'
        white: '0xf5f5f5'
selection:
    unfocused_hollow: true
mouse:
    hide_when_typing: true
shell:
    program: /usr/bin/fish
window:
    padding:
        x: 36
        y: 36
scrolling:
    history: 100000
    multiplier: 4

font:
    normal:
        family: JetBrainsMono Nerd Font
    size: 12
background_opacity: 1.0
