workspace $ws1 output DP-0
workspace $ws2 output DP-4
workspace $ws3 output DP-0
workspace $ws4 output DP-4
workspace $ws5 output DP-0
workspace $ws6 output DP-4
workspace $ws7 output DP-0
workspace $ws8 output DP-4
workspace $ws9 output DP-0
workspace "Spotify" output DP-0
